version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: property
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    working_dir: /app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: 